=== mironsoft75/magento-3/migration/data-migration-tool/etc/split_combine_process.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="split" type="splitType" />
    <xs:complexType name="splitType">
        <xs:sequence>
            <xs:element name="settings" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="source" maxOccurs="1" minOccurs="0" >
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="combine" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="sections" maxOccurs="unbounded" minOccurs="0">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="documents" maxOccurs="unbounded" minOccurs="0">
                                                                <xs:complexType>
                                                                    <xs:sequence>
                                                                        <xs:element name="from" maxOccurs="unbounded" minOccurs="0"/>
                                                                        <xs:element name="to" maxOccurs="unbounded" minOccurs="0"/>
                                                                    </xs:sequence>
                                                                </xs:complexType>
                                                            </xs:element>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="ignore" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                            <xs:choice minOccurs="1" maxOccurs="unbounded">
                                                <xs:element name="field" type="xs:string" maxOccurs="unbounded" minOccurs="0" />
                                            </xs:choice>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="move"  maxOccurs="unbounded"  minOccurs="0">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="field"  maxOccurs="unbounded" minOccurs="0" />
                                                <xs:element name="to" type="xs:string" maxOccurs="unbounded" minOccurs="0" />
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="destination" maxOccurs="1" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="ignore" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                            <xs:choice maxOccurs="unbounded" minOccurs="1">
                                                <xs:element name="field" type="xs:string" maxOccurs="unbounded" minOccurs="0" />
                                                <xs:element name="datatype" type="xs:string" maxOccurs="unbounded" minOccurs="0" />
                                            </xs:choice>
                                        </xs:complexType>
                                    </xs:element>
                                    <!--  -->
                                    <xs:element name="foreign_key" maxOccurs="unbounded" minOccurs="0">
                                        <xs:complexType>
                                            <xs:choice maxOccurs="unbounded" minOccurs="1">
                                                <xs:element name="this" type="xs:string" maxOccurs="1" minOccurs="0" />
                                                <xs:element name="to_that" type="xs:string" maxOccurs="1" minOccurs="0" />
                                            </xs:choice>
                                        </xs:complexType>
                                    </xs:element>
                                    <!-- -->
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="from" maxOccurs="1" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="documents"  maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="document" type="xs:string" maxOccurs="unbounded"  minOccurs="0"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="fields"  maxOccurs="1" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="field"  maxOccurs="unbounded"  minOccurs="0"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="transfer" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="document" maxOccurs="unbounded" minOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== mironsoft75/magento-3/migration/data-migration-tool/etc/opensource-to-opensource/1.9.3.10/combine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<split xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../split.xsd">-->
<split xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
       xs:noNamespaceSchemaLocation="../../split_combine_process.xsd">
    <settings>
        <source>
            <move>
                <field>migration_combine_me_table_1.account_id</field>
                <to>migration_combine_me_table.account_id</to>
            </move>
            <move>
                <field>migration_combine_me_table_2.lastname_connect</field>
                <to>migration_combine_me_table.lastname_connect</to>
            </move>
            <move>
                <field>migration_combine_me_table_2.age</field>
                <to>migration_combine_me_table.age</to>
            </move>
            <move>
                <field>migration_combine_me_table_2.is_new</field>
                <to>migration_combine_me_table.is_new</to>
            </move>
        </source>
    </settings>
    <from>
        <documents>
            <document>migration_combine_me_table_1</document>
        </documents>
        <documents>
            <document>migration_combine_me_table_2</document>
        </documents>
    </from>
    <transfer>
        <document>migration_combine_me_table</document>
    </transfer>
</split>

=== mironsoft75/magento-3/migration/data-migration-tool/etc/opensource-to-opensource/1.9.3.10/split.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<split xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../split.xsd">-->
<split xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="../../split_combine_process.xsd">
    <settings>
        <source>
            <ignore>
                <field>migration_split_me_table.is_new</field>
                <field>migration_split_me_table.value</field>
                <!--<field>migration_split_me_table.id</field>-->
                <!--<field>migration_split_me_table.account_id_split_1</field>-->
            </ignore>
            <move>
                <field>migration_split_me_table.id</field>
                <to>migration_split_me_table_person.to_move_test</to>
            </move>
            <move>
                <field>migration_split_me_table.id</field>
                <to>migration_split_me_table_person.main_table_id</to>
            </move>
            <!---->
            <!--<move>-->
                <!--<field>migration_combine_me_table_1.account_id</field>-->
                <!--<to>migration_combine_me_table.account_id</to>-->
            <!--</move>-->
            <!--<move>-->
                <!--<field>migration_combine_me_table_2.lastname_connect</field>-->
                <!--<to>migration_combine_me_table.lastname_connect</to>-->
            <!--</move>-->
            <!--<move>-->
                <!--<field>migration_combine_me_table_2.age</field>-->
                <!--<to>migration_combine_me_table.age</to>-->
            <!--</move>-->
            <!--<move>-->
                <!--<field>migration_combine_me_table_2.is_new</field>-->
                <!--<to>migration_combine_me_table.is_new</to>-->
            <!--</move>-->
            <!---->
        </source>
        <destination>
            <ignore>
                <datatype>migration_split_me_table_person.account_id_split_1</datatype>
                <datatype>migration_split_me_table_person.name_split_1</datatype>
            </ignore>
            <ignore>
                <!--<field>migration_split_me_table_person.to_move_test</field>-->
            </ignore>
            <ignore>
                <!--<field>migration_split_me_table_person.main_table_id</field>-->
            </ignore>
        </destination>
    </settings>
    <from>
        <documents>
            <document>migration_split_me_table</document>
        </documents>
    </from>
    <transfer>
        <document>migration_split_me_table_main</document>
        <document>migration_split_me_table_person</document>
    </transfer>
</split>
